# Generated by Django 6.1.1 on 2026-09-15 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productvariant_options_remove_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on homepage (lower numbers appear first)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='shop.product')),
            ],
            options={
                'verbose_name': 'Featured Product',
                'verbose_name_plural': 'Featured Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on homepage (lower numbers appear first)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_entries', to='shop.product')),
            ],
            options={
                'verbose_name': 'New Product',
                'verbose_name_plural': 'New Products',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on homepage (lower numbers appear first)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_entries', to='shop.product')),
            ],
            options={
                'verbose_name': 'Offer Product',
                'verbose_name_plural': 'Offer Products',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
