# Generated by Django 6.1.1 on 2026-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_featuredproduct_newproduct_offerproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Specification'),
        ),
    ]
